* Simulation code and data for /Workers’ sons rescue genetic diversity at the sex locus in an invasive honey bee population/ by Gloag et al (2019), published in [[https://onlinelibrary.wiley.com/doi/abs/10.1111/mec.15031][Molecular Ecology].

** Manuscript data and analysis script

Raw simulation data for the manuscript are in ~manuscript_data/~ as ~.RData~ files. To replicate the analysis of the simulations, run the analysis script by entering ~source('analysis.R')~ into an ~R~ terminal (first ensuring that your working directory points to the directory containing the scripts---you can change your working directory using the ~setwd('/insert/the/path/here')~ function). After running ~analysis.R~, the summary file will appear in ~manuscript_data/~. All data in the manuscript pertaining to simulation results are contained within ~/manuscript_data/data_summary.csv~.

** Running simulations with new sets of parameter values

To run simulations with your own sets of parameter values, you can alter the parameter values at the top of ~worker_reproduction_script.R~. You can then run the simulations using ~source('worker_reproduction_script.R')~. Any simulations that you run will show up in ~user_data/~ as ~.RData~ files. You can analyse the data in these simulations by running ~analysis.R~, but you'll first need to uncomment line 19 (its default behaviour is to analyse data in ~manuscript_data/~, reproducing the analysis in the manuscript). A summary file will appear in ~user_data/~.
