* Simulation code and data for /Workers’ sons rescue genetic diversity at the sex locus in an invasive honey bee population/ by Gloag et al.

** Manuscript data and analysis script

Simulation data for the manuscript is in ~manuscript_data/~. To produce a summary file of the data, run the analysis script by entering ~source('analysis.R')~ into an ~R~ terminal (first ensuring that your working directory points to the directory containing the scripts---you can change your working directory using the ~setwd('/insert/the/path/here')~ function). After running ~analysis.R~, the summary file will appear in ~manuscript_data/~.

** Running simulations with new sets of parameter values

To run simulations with your own sets of parameter values, you can alter the parameter values at the top of ~worker_reproduction_script.R~ (using ~source('worker_reproduction_script.R')~). Any simulations that you run will show up in ~user_data/~ as ~.RData~ files. You can analyse the data in these simulations by running ~analysis.R~, but you'll first need to uncomment line 19 (its default behaviour is to analyse data in ~/manuscript_data/~, reproducing the analysis in the manuscript).
